# Generated by Django 5.2.6 on 2026-01-28 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0007_product_color_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('p', 'paint'), ('j', 'jeans'), ('t', 't-shirt'), ('s', 'shirt'), ('T', 'toper')], default='s', max_length=50),
        ),
    ]
